// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "petStore/internal/logic/money"
	_ "petStore/internal/logic/user"
)
