// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"petStore/internal/model"
)

type (
	IAuth interface {
		ValidateJWTToken(ctx context.Context, in model.JWTValidateInput) error
		QueryAccessToken(ctx context.Context, in model.AccessTokenQueryInput) (*model.AccessTokenQueryOutput, error)
		QueryRefreshToken(ctx context.Context, in model.RefreshTokenQueryInput) (*model.RefreshTokenQueryOutput, error)
		IssueAccessToken(ctx context.Context, in model.AccessTokenIssueInput) (*model.AccessTokenIssueOutput, error)
		IssueRefreshToken(ctx context.Context, in model.RefreshTokenIssueInput) (*model.RefreshTokenIssueOutput, error)
	}
)

var (
	localAuth IAuth
)

func Auth() IAuth {
	if localAuth == nil {
		panic("implement not found for interface IAuth, forgot register?")
	}
	return localAuth
}

func RegisterAuth(i IAuth) {
	localAuth = i
}
