// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"petStore/internal/model"
)

type (
	IAuth interface {
		ValidateJwtToken(ctx context.Context, in model.JwtValidateInput) error
		QueryJwtToken(ctx context.Context, in model.JwtQueryInput) (*model.JwtQueryOutput, error)
		IssueJwtToken(ctx context.Context, in model.JwtIssueInput) (*model.JwtIssueOutPut, error)
	}
)

var (
	localAuth IAuth
)

func Auth() IAuth {
	if localAuth == nil {
		panic("implement not found for interface IAuth, forgot register?")
	}
	return localAuth
}

func RegisterAuth(i IAuth) {
	localAuth = i
}
