// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"petStore/internal/model"
)

type (
	IUser interface {
		CookieValidate(ctx context.Context, in model.UserCookiesInput) error
		CreateUser(ctx context.Context, in model.UserRegisterInput) error
		Login(ctx context.Context, in model.UserLoginInput) error
		UserValidate(ctx context.Context, in model.UserValidateInput) error
		UserSetLastLogin(ctx context.Context, in model.UserSetLastLoginInput) error
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
